### ISSUE TITLE
Last version support?

### ISSUE THREAD

**Issue by jlstanus** [sourcepole/qgis-wps-client#12]
Support for last versions are not OK

Which is the last QGIS Version compatible?
Will that plugin updated?

> Impossible de charger l'extension 'wps' provoque une erreur lors de l'appel à sa méthode classFactory() 
> 
> Traceback (most recent call last):
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\__init__.py", line 50, in classFactory
>     from .qgswps import QgsWps
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\qgswps.py", line 23, in 
>     from .QgsWpsDockWidget import QgsWpsDockWidget
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\QgsWpsDockWidget.py", line 26, in 
>     from .qgswpsgui import QgsWpsGui
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\qgswpsgui.py", line 26, in 
>     from .wpslib.wpsserver import WpsServer
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\wpslib\wpsserver.py", line 29, in 
>     from ..apicompat.sipv2.compat import pystring
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\__init__.py", line 2, in 
>     from . import apicompat
>   File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\apicompat.py", line 34, in 
>     if sipv1():
>   File "C:\Users/stanusjl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wps\apicompat\apicompat.py", line 30, in sipv1
>     return sip.getapi("QVariant") == 1
> ValueError: unknown API 'QVariant'
> 
> 
> Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
> Version de QGIS : 3.28.8-Firenze Firenze, 5ac45272b5

**Comment by hdus** [comment]
The plugin was never properly ported to QGIS 3 because there was no funding for it. A few updates have come from the community, but a professional migration has never taken place. If you are interested in migrating the plugin, I would be happy to make you an offer.
